### ISSUE TITLE
PostChatMessage gives channel_not_found error after upgrade from 0.2.6 -> 0.2.7

### ISSUE THREAD

**Issue by MichelEdkrantz** [slack-scala-client/slack-scala-client#108]
Hi, 
we just upgraded from 0.2.6 to 0.2.7 and are now getting errors from slack with channel_not_found when trying to post chat messages like

`client.postChatMessage(channelId, msg)`

```
slack.api.ApiError: channel_not_found
	at slack.api.SlackApiClient$.$anonfun$makeApiRequest$2(SlackApiClient.scala:71)

```

It seems the call has changed internally from a GET request to POST. 

Do you have any idea what might have cause this issue?

**Comment by LyndonArmitage** [comment]
Recently found the library and was struggling to use it because of this.

**Comment by daniel-bytes** [comment]
I believe this is caused by a missing / wrong `Content-Type` header.  It should be `Content-type: application/json; charset=utf-8`, see [this Reddit post](https://www.reddit.com/r/Slack/comments/apsmy7/why_i_am_getting_all_the_time_channel_not_found/egdi2wp) for example.

**Comment by LyndonArmitage** [comment]
Awesome Daniel!

Apologies for my short "me too" message, I didn't get a chance to debug further, I did want to check what the actual HTTP requests were being sent.

**Comment by MichelEdkrantz** [comment]
Thanks @daniel-bytes and @mccartney 
What's the timeline for the next release?

**Comment by mccartney** [comment]
I can take care of releasing soon if there's a need.

**Comment by mccartney** [comment]
`0.2.8` is just being released (should be available in a few hours everywhere)
