### ISSUE TITLE
Pekko variant?

### ISSUE THREAD

**Issue by MichelEdkrantz** [slack-scala-client/slack-scala-client#273]
Hi!
Thanks for this great lib :) Now that Pekko 1.0 has been released, is there any interest from your end to provide a pekko variant of this?

https://github.com/apache/incubator-pekko

**Comment by mccartney** [comment]
I think that's a good idea. I haven't tried it yet. Up for grabs.

Not sure if we can afford to switch to pekko (provided that it works) or it has to be a variant as you say.

**Comment by mccartney** [comment]
Instead of a variant, I am trying to just migrate to Pekko and drop Akka.
