### ISSUE TITLE
Update Akka HTTP

### ISSUE THREAD

**Issue by majk-p** [slack-scala-client/slack-scala-client#87]
Hi,
First of all - thanks for the great library, It works like a charm. I'd like to use it with latest akka-actor package, but it seems that due to the dependency on akka http v10.0.11, akka-actor is resolved to v2.4.20
```
[info] downloading https://repo1.maven.org/maven2/com/github/slack-scala-client/slack-scala-client_2.12/0.2.5/slack-scala-client_2.12-0.2.5.jar ...
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.4.20/akka-actor_2.12-2.4.20.jar ...
```
I've managed to make a workaround following this issue: https://github.com/akka/akka-http/issues/1876.
As mentioned in [akka http compatibility guidelines](https://doc.akka.io/docs/akka-http/current/compatibility-guidelines.html#specific-versions-inter-op-discussion) it's possible to explicitly provide akka-actor and akka-stream versions to be used, as they are binary compatible. The workaround form the docs worked well:
```sbt
val akkaVersion = "2.5.19"
val akkaHttpVersion = "10.1.7"
libraryDependencies += "com.typesafe.akka" %% "akka-http"   % akkaHttpVersion
libraryDependencies += "com.typesafe.akka" %% "akka-actor"  % akkaVersion
libraryDependencies += "com.typesafe.akka" %% "akka-stream" % akkaVersion
// If testkit used, explicitly declare dependency on akka-streams-testkit in same version as akka-actor
libraryDependencies += "com.typesafe.akka" %% "akka-http-testkit"   % akkaHttpVersion % Test
libraryDependencies += "com.typesafe.akka" %% "akka-stream-testkit" % akkaVersion     % Test
```

This workaround can be avoided if the akka-http version would be updated. Can you please implement that?

**Comment by mccartney** [comment]
What I noticed is that although we define versions for both `akka-http` and `akka-actor`. The latter is never used, so it simply must be the `akka-http` bringing it `actor` as a dependency of its own.

Let me try to upgrade the `akka-http` and see how it goes.

**Comment by mccartney** [comment]
The upgrade went smooth for me. 
Sorry for a slow response. Next time you can submit a PR, so it goes quicker.
