### ISSUE TITLE
Upgrade Play 2.7

### ISSUE THREAD

**Issue by dispalt** [slack-scala-client/slack-scala-client#89]
I was hoping to use this with play 2.7 but their is a binary compat issue.  Would you prefer to publish a 0.2.5-play27 artifact or would you just publish a new 0.2.6 for play-json 2.7?

**Comment by mccartney** [comment]
I'd rather avoid adding another variant with `play` version. I am not an expert in `play`, but we are using only its json parsing capabilities. So let me just upgrade the `play` dependency.

**Comment by dispalt** [comment]
Thanks btw!
